onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
